### ISSUE TITLE
Sample uses Closeable instead of OnClearedListener

### ISSUE THREAD

**Issue by grodin** [marcellogalhardo/retained#82]
This is incredibly minor, but the sample project has a retained instance which implements `Closeable` and I'm pretty certain it should implement `OnClearedListener` instead.

Thanks for this library by the way. The boilerplate associated with `ViewModel` is just irritating noise most of the time and this library eliminates it totally!

**Comment by marcellogalhardo** [comment]
@grodin you are correct, originally we used `Closeable` but end up creating our own `OnClearedListener` due to the [auto-subscription](https://github.com/marcellogalhardo/retained/blame/master/README.md#L147).

Feel free to submit a PR fixing, otherwise I will fix it later. Thank you for reporting it!
